sulu_media:
    resource: "@SuluMediaBundle/Resources/config/routing_website.yml"

sulu_search:
    type: portal
    resource: "@SuluSearchBundle/Resources/config/routing_website.xml"

sulu_website:
    resource: "@SuluWebsiteBundle/Resources/config/routing_website.yml"

example_news:
    resource: "@ExampleNewsBundle/Controller/"
    type:     annotation
    prefix:   /
